# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - build
  - test
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  APT_CACHE_DIR: .apt-cache

build:
  stage: build
  cache:
    paths:
      - .cargo
  script:
    - cargo install wasm-pack
    - rustc --version && cargo --version  && ./.cargo/bin/wasm-pack --version # Print version info for debugging
    - ./.cargo/bin/wasm-pack build --target web --out-name wasm --out-dir ./static
  artifacts:
    expire_in: 2 days
    paths:
      - static/
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'      # Execute jobs when a new commit is pushed to main branch


# Use cargo to test the project
test:cargo:
  stage: test
  cache:
    paths:
      - .cargo
      - .apt-cache
  script:
    - cargo test --features no-wasm

  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'main'      # Execute jobs when a new commit is pushed to main branch


pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - "mv static/ public/"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'      # Execute jobs when a new commit is pushed to main branch

  