# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo


before_script:
  - cargo install wasm-pack
  - cargo install cargo-make

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version  && wasm-pack --version # Print version info for debugging
    - wasm-pack test --firefox --headless
  cache:
    paths:
      - .cargo

