# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  APT_CACHE_DIR: .apt-cache


before_script:
  - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
  - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
    firefox-esr
  - firefox --version
  - cargo install wasm-pack
  - cargo install cargo-make

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version  && ./.cargo/bin/wasm-pack --version # Print version info for debugging
    -  ./.cargo/bin/wasm-pack test --firefox --headless
  cache:
    paths:
      - .cargo
      - .apt-cache

