[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.wasm_build]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]

[tasks.wasm_build_dev]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]


[tasks.test]
command = "wasm-pack"
args = ["test", "--firefox", "--headless"]

[tasks.build_web]
dependencies = [
    "wasm_build"
]

[tasks.build_web_dev]
dependencies = [
    "wasm_build_dev"
]

[tasks.serve]
command = "miniserve"
args = ["./static", "--index", "index.html"]
dependencies = ["build_web"]

[tasks.serve_dev]
command = "miniserve"
args = ["./static", "--index", "index.html"]
dependencies = ["build_web_dev"]
