[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.wasm_build]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
dependencies = ["clean_web"]

[tasks.wasm_build_profileing]
command = "wasm-pack"
args = ["build", "--profiling", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
dependencies = ["clean_web"]

[tasks.wasm_build_dev]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
dependencies = ["clean_web"]

[tasks.test]
command = "wasm-pack"
args = ["test", "--firefox", "--headless"]

[tasks.build]
dependencies = [
    "wasm_build"
]

[tasks.clean_web]
script_runner = "@shell"
script = ["rm -f ./static/*wasm*"]

[tasks.serve_web]
command = "miniserve"
args = ["./static", "--index", "index.html"]

[tasks.serve]
dependencies = ["wasm_build", "serve_web"]

[tasks.serve_dev]
dependencies = ["wasm_build_dev", "serve_web"]

[tasks.serve_profileing]
dependencies = ["wasm_build_profileing", "serve_web"]
